[tool.poetry]
name = "zakovat-online"
version = "0.1.0"
description = ""
authors = ["Арсен Маматбаев <arsenmamatbaev@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
